export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <p className="text-pink-500 text-xl">Blog Layout</p>
      {children}
    </section>
  );
}
