import "./globals.css"
import { Inter } from "next/font/google"
import NavBar from "./navbar"
import { Providers } from "./providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-xl bg-white dark:bg-black">
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
